### PR TITLE
Added .Net 4.5 & async/await functionality

### PR DESCRIPTION
**Pull request by jbattermann**
Added a new DapperExtensions.Net45 project that works exactly like Dapper for .Net 4.5 works: links all the .Net 4.0 files in and only adds an async/await compatible set on top / beside (see the two DapperAsync*.cs files).

Internally the very same sql statement builders are used as the non-async ones use, the only really addition is the underlying usage of the corresponding Dapper QueryAsync<T>(..) methods rather than the synchronous one(s). Therefore the buffer paramater has been removed as Dapper itself does not offer it for the async QueryAsync one.

Updated Dapper Nuget Package to 1.34 (the current) one along the line because async/await support in Dapper itself has improved since the originally used 1.13 version.

I attempted to 'emulate' the existing code-style as much as I could and not change the base mechanics (particularly the factory mechanics inside the *Extensions.cs file(s)).

One last thing - I also added the 'net45' entries in the the DapperExtensions.nuspec file, the later still resides in the normal DapperExtensions directory.. but I didn't want to move it out of there (not sure if/what kind of build system you have in place that maybe uses that path etc etc).

Cheers,
-J

### CODE REVIEW

**Comment by lommez** [comment]
This pull request is very important to me. Is going to be accepted?
Thanks

**Comment by billzhuang** [comment]
this PR is also good to use in my rode, can merge it?

**Comment by jbattermann** [comment]
@billzhuang because none of those are part of the core Dapper.Net library, they are in the Dapper.Contrib one.. which the Dapper-Extensions library here does not reference/use & basically they overlap to a certain extent.

However, as this library and PR of Dapper-Extensions have been laying dormant for months now, I have no intention of spending more time on it, sorry.

**Comment by billzhuang** [comment]
@jbattermann tks for your work, but i'm a little bit  confused about what you said that "Insert/Update in in Dapper.Contrib one", for example, pls take a look this line of code in current repo, https://github.com/tmsmith/Dapper-Extensions/blob/master/DapperExtensions/DapperExtensions.cs#L148

**Comment by jbattermann** [comment]
@billzhuang Bill, my changes built upon the actual Async() support / -methods in the core [Dapper library](https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper NET45/SqlMapperAsync.cs) (and only the core library) and correspondingly only Async() methods available in Dapper Core are mapped over to this Dapper-Extensions PR. As there is no native InsertAsync() method in Dapper itself, there was nothing I could use here.

Dapper.Contrib on the other hand [DOES provide Async Inserts etc](https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper.Contrib%20NET45/SqlMapperExtensionsAsync.cs), but as stated before, Dapper.Contrib and Dapper-Extensions overlap in their functionality. If you want/need it mapped over to Dapper-Extensions, you can take my PR and extend it and you should be fine.

**Comment by billzhuang** [comment]
aha, got it, tks~

**Comment by scrooby** [comment]
Great work, it would be very useful to get this merged in.

**Comment by jbattermann** [comment]
A blast from the past 😃 but nice to see it got pulled in 👍 Thanks @tmsmith  & @IsotrakMP

**Comment by lommez** [comment]
Thank you!!!

**Pull request merged**
