### PR TITLE
Feature/dot net core2

### PR DESCRIPTION
**Pull request by ZaChickster**
Simply followed existing methodology via linked files to create a .NET Core version of this project.

### CODE REVIEW

**Comment by guy-lud** [comment]
Hi @ZaChickster, 
Do you know if Dapper-Extensions is a "Orphan" projects ?
I've made some pull request myself, yet i see that a lot of Pull request are not answered.

**Comment by ZaChickster** [comment]
Yeah, we noticed that as well.  The POCO based usage was appealing so we used it anyway.  Were you thinking of contacting @tmsmith?

**Comment by tmsmith** [comment]
The project is not Orphaned. I have not pulled in dotnet Core as I have not had much time to work with it.

**Comment by ZaChickster** [comment]
No worries @tmsmith.  If you need any help we're willing to lend a hand.

**Comment by guy-lud** [comment]
@tmsmith thanks for the reply, if you need an and just let us know

**Comment by hpbieker** [comment]
Any updates here?

**Comment by ZaChickster** [comment]
Doesn't appear to be.  We've been using this forked version against our .NET Core 2.0 app with no real issues.  Granted we're not doing anything super sophisticated.

**Comment by riyajshaikh09** [comment]
is it available to use?? i want to use Dapper in my .Net core application.

**Comment by ZaChickster** [comment]
We're using this fork with no issues.  Predicate stuff doesn't work but the
rest does.

**Comment by riyajshaikh09** [comment]
@ZaChickster i am new to git can you please let me know how i can get Feature/dot net core2.

**Comment by lommez** [comment]
Any news about this PR? I'm having problems to use Dapper in .Net Core 2.1

**Comment by ZaChickster** [comment]
We haven't had any issues with this fork in 2.1 but granted we're not doing the sophisticated predicate stuff.  No word on if or when anything will get merged.  While we'd prefer the fork get merged we're ok working off our own copy.

**Comment by valfrid-ly** [comment]
There will be a version with more recent net core

**Pull request closed without merging**
