### PR TITLE
Do not generate Guid id when one is passed in

### LINKED ISSUE #74: Inserting KeyType.Guid ALWAYS creates new Guid
Any chance you can make a change so that when the Id already has a value passed into the Insert method, the Insert does not overwrite it?

```
if (column.KeyType == KeyType.Guid )
{
    Guid comb = SqlGenerator.Configuration.GetNextGuid();
    column.PropertyInfo.SetValue(e, comb, null);
}
```

I am importing data from another source, and I would like to keep the ids the same. But I am also creating new records, so I would like Guids generated when the Id is not set.

### PR DESCRIPTION
**Pull request by MLaritz**
This change fixes #74.  If the Primary Key is a Guid, and it contains a value (other than Guid.Empty), that Id will be inserted and a new one will not be generated.

### CODE REVIEW

**Comment by Ermesx** [comment]
Please merge this :+1:

**Comment by ashock** [comment]
Can we please have this merged or added the additional key option. I have may cases were the primary guid key is supplied, replication of database across different repository types for example. I don't want new id being generated.

**Comment by ryclarky** [comment]
Also looking for a merge here.  This seems like functionality that should be supported.  I have a table with the primary key being a guid, but I want to specify the guids that get inserted but cannot.  I have to create another column and index and just complete ignore the primary key field which just takes up space for no reason.

**Comment by khoiquyenvn** [comment]
Please merge this. Thanks

**Comment by ryanelian** [comment]
I was confused why the GUID output didn't match until I directly look into the tables.

Please merge this pull?

**Comment by sjdweb** [comment]
Why is this not merged in?

**Comment by Ermesx** [comment]
💯

**Pull request merged**
