### PR TITLE
Support for .NET Standard 2.0 (and .NET Core) + multi-targeting project + nuget packaging

### PR DESCRIPTION
**Pull request by rlreis90**
Created a new project (and solution) multi-targeting .NET Framework 4, 4.5 and Standard.
Also pre-configured it to generate a NuGet Package for all versions on build. **

(** Note: this ONLY replicates the previous nuspec into a new format; no versioning-related changes have been made. Those need to be made separately.)

### CODE REVIEW

**Comment by davidbuckleyni** [comment]
I would be interested in getting a copy of this do u have ur own fork @rlreis90  I need .net standard support for xamrian ?

**Comment by rlreis90** [comment]
Yes, you can follow the link below the title.

**Comment by brookpatten** [comment]
Is this project dead?  It would be really nice to see this core support get merged.

**Comment by davidbuckleyni** [comment]
> Is this project dead? It would be really nice to see this core support get merged.

You could always fork it and make urself but @rlreis90  already said in above answer

**Comment by brookpatten** [comment]
> 
> You could always fork it and make urself but @rlreis90 already said in above answer

Sure but I (and likely most other users of it) would rather subscribe to a maintained package.  Perhaps it's time to consider adding some new folks as maintainers?  Seems like there's lots of people submitting PR's...

**Comment by valfrid-ly** [comment]
There is a ongoing version with this feature without creating a new project

**Pull request closed without merging**
